// Run with Node.js 18+. Browser and live Flow integration are separate tests.
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const base=path.join(__dirname,'..');
(async()=>{
 const records={},events={},downloads=new Map();let nextId=1,lastOptions;
 const chrome={action:{onClicked:{addListener:f=>events.action=f},setBadgeText:async()=>{}},tabs:{sendMessage:async()=>{}},scripting:{executeScript:async()=>{}},runtime:{onMessage:{addListener:f=>events.message=f}},storage:{session:{get:async k=>({[k]:records[k]}),set:async d=>Object.assign(records,d),remove:async k=>delete records[k]}},downloads:{download:async o=>{lastOptions=o;const id=nextId++;downloads.set(id,{id,state:'in_progress',bytesReceived:0,totalBytes:100});return id;},search:async({id})=>[downloads.get(id)],show:()=>{},onDeterminingFilename:{addListener:f=>events.filename=f}}};
 vm.runInNewContext(fs.readFileSync(path.join(base,'background.js'),'utf8'),{chrome,URL,Date,console});
 const send=(m,tabId=1)=>new Promise(resolve=>events.message(m,{tab:{id:tabId},url:'https://labs.google/fx/tools/flow/project/test'},resolve));
 assert.equal((await send({type:'BEGIN'})).ok,true);
 assert.equal((await send({type:'BEGIN'},2)).ok,false,'other tab cannot take active batch');
 const folder='flow下载2026-09-11_21-35-08';
 let r=await send({type:'DOWNLOAD',folder,url:'https://flow-content.google/video/example',kind:'video',base:'001_测试:视频_原始大小',originalName:'original.webm'});
 assert.equal(r.ok,true);assert.equal(lastOptions.saveAs,false);assert.equal(lastOptions.filename,folder+'/001_测试_视频_原始大小.webm');
 assert.equal((await send({type:'STATUS',id:r.id},2)).ok,false);
 assert.equal((await send({type:'STATUS',id:r.id})).state,'in_progress');downloads.get(r.id).state='complete';assert.equal((await send({type:'STATUS',id:r.id})).state,'complete');
 assert.equal((await send({type:'DOWNLOAD',folder:'../outside',url:'https://x.test/file',base:'a'})).ok,false);
 assert.equal((await send({type:'DOWNLOAD',folder,url:'file:///etc/passwd',base:'a'})).ok,false);
 assert.equal((await send({type:'DOWNLOAD',folder,url:'blob:https://unrelated.test/id',base:'a'})).ok,false);
 await send({type:'ARM_NATIVE',folder,url:'blob:https://labs.google/one',base:'002_photo_1K'});
 const suggest=item=>new Promise(resolve=>events.filename(item,resolve));
 assert.equal(await suggest({id:10,url:'blob:https://labs.google/unrelated',filename:'x.png'}),undefined,'unrelated download unchanged');
 let s=await suggest({id:11,url:'blob:https://labs.google/one',filename:'original.png'});assert.equal(s.filename,folder+'/002_photo_1K.png');
 assert.equal((await send({type:'NATIVE_STATUS'})).id,11);
 assert.equal(await suggest({id:12,url:'blob:https://labs.google/one',filename:'original.png'}),undefined,'never claim twice');
 // Uncaptured native media URL, refreshed signatures, prompt-only name, and final folder verification.
 await send({type:'EXPECT',token:'job-x',folder,url:'https://flow-content.google/video/video-id?old=1',kind:'video',base:'人物在练习唱歌'});
 s=await suggest({id:13,url:'https://flow-content.google/video/video-id?new=2',filename:'server-name.mp4',mime:'video/mp4'});
 assert.equal(s.filename,folder+'/人物在练习唱歌.mp4');assert.equal(s.conflictAction,'uniquify');
 assert.equal((await send({type:'EXPECT_STATUS',token:'job-x'})).id,13);
 downloads.set(13,{state:'complete',filename:'C:\\Users\\User\\Downloads\\'+folder+'\\人物在练习唱歌.mp4'});
 assert.equal((await send({type:'STATUS',id:13})).savedCorrect,true);
 downloads.get(13).filename='C:/Users/User/Downloads/人物在练习唱歌.mp4';assert.equal((await send({type:'STATUS',id:13})).savedCorrect,false);
 await send({type:'CLEAR_EXPECT',token:'job-x'});assert.equal((await send({type:'EXPECT_STATUS',token:'job-x'})).id,null);
 console.log('PASS native HTTPS download, prompt-only filename, collision numbering option, Windows folder verification and wrong-directory detection');
 console.log('PASS background: folders, extension preservation, progress, ownership, invalid URLs, exact native matching');
 let messageHandler,clickHandler;const posts=[],nativeClicks=[],revokes=[];
 function Anchor(href,download=''){this.href=href;this.download=download;}Anchor.prototype.click=function(){nativeClicks.push(this.href)};Anchor.prototype.hasAttribute=function(n){return n==='download'&&!!this.download};
 const window={addEventListener:(n,f)=>messageHandler=f,postMessage:m=>posts.push(m)},location={origin:'https://labs.google'};
 const URLmock={revokeObjectURL:u=>revokes.push(u)};
 vm.runInNewContext(fs.readFileSync(path.join(base,'bridge.js'),'utf8'),{window,location,HTMLAnchorElement:Anchor,URL:URLmock,document:{addEventListener:(n,f)=>clickHandler=f},Date,Set});
 const ctl=m=>messageHandler({source:window,origin:location.origin,data:{channel:'FLOW_DL_CONTROL',...m}});
 new Anchor('https://elsewhere.test/').click();assert.equal(nativeClicks.length,1);
 ctl({type:'ARM',token:'a'});assert.equal(posts.at(-1).type,'READY');
 new Anchor('https://elsewhere.test/').click();assert.equal(nativeClicks.length,2,'normal navigation not captured');
 const a=new Anchor('blob:https://labs.google/image','original.png');a.click();assert.equal(posts.at(-1).type,'CAPTURE');assert.equal(nativeClicks.length,2);
 URLmock.revokeObjectURL(a.href);assert.equal(revokes.length,0,'blob kept alive');
 ctl({type:'NATIVE',token:'wrong'});assert.equal(nativeClicks.length,2);
 ctl({type:'NATIVE',token:'a'});assert.equal(nativeClicks.length,3);
 ctl({type:'RELEASE',url:a.href});assert.deepEqual(revokes,[a.href]);
 ctl({type:'ARM',token:'b'});const before=posts.length;
 clickHandler({isTrusted:true,target:{closest:()=>new Anchor('https://flow-content.google/image/user','user.png')}});assert.equal(posts.length,before,'real user click untouched');
 console.log('PASS bridge: scoped capture, untouched navigation, Blob lifetime, native retry, trusted click');
 const manifest=JSON.parse(fs.readFileSync(path.join(base,'manifest.json')));assert.equal(manifest.manifest_version,3);for(const f of ['background.js','content.js','bridge.js'])new vm.Script(fs.readFileSync(path.join(base,f),'utf8'),{filename:f});
 console.log('PASS manifest and JavaScript syntax');
})().catch(e=>{console.error(e);process.exitCode=1});
